const flagImages = {
  SP: require('../assets/flags/SP.jpg'),
  AC: require('../assets/flags/AC.jpg'),
  AL: require('../assets/flags/AL.jpg'),
  AM: require('../assets/flags/AM.jpg'),
  AP: require('../assets/flags/AP.jpg'),
  BA: require('../assets/flags/BA.jpg'),
  CE: require('../assets/flags/CE.jpg'),
  DF: require('../assets/flags/DF.jpg'),
  ES: require('../assets/flags/ES.jpg'),
  GO: require('../assets/flags/GO.jpg'),
  MA: require('../assets/flags/MA.jpg'),
  MG: require('../assets/flags/MG.jpg'),
  MS: require('../assets/flags/MS.jpg'),
  MT: require('../assets/flags/MT.jpg'),
  PA: require('../assets/flags/PA.jpg'),
  PB: require('../assets/flags/PB.jpg'),
  PE: require('../assets/flags/PE.jpg'),
  PI: require('../assets/flags/PI.jpg'),
  PR: require('../assets/flags/PR.jpg'),
  RJ: require('../assets/flags/RJ.jpg'),
  RN: require('../assets/flags/RN.jpg'),
  RO: require('../assets/flags/RO.jpg'),
  RR: require('../assets/flags/RR.jpg'),
  RS: require('../assets/flags/RS.jpg'),
  SC: require('../assets/flags/SC.jpg'),
  SE: require('../assets/flags/SE.jpg'),
  TO: require('../assets/flags/TO.jpg'),
};

export default flagImages;
